# Laboratorio 3

## Task 1

1. ¿Qué es Programación Dinámica y cómo se relaciona con RL?
   La programación Dinámica se puede describir como una técnica de optimización para resolver problemas complejos en donde estos se dividen en subproblemas más simples, para esto se utilizan problemas que puedan mediante una estructura que sea recursiva. En el contexto de RL la programación dinámica se aplica para resolver problemas de decisión secuencial, donde un agente aprende a tomar decisiones para maximizar la recompensa acumulada a lo largo del tiempo, los algoritmos de programación dinámica como la iteración de valor y la iteración de póliza son métodos que se utilizan para encontrar políticas optimas y valores de estado.

2. Explique en sus propias palabras el algoritmo de Iteración de Póliza.
   En nuestras palabras el algoritmo de póliza se puede describir como un algoritmo de programación dinámica para encontrar una política optima el cual consiste dn dos pasos principales que se repiten varias veces siendo esta la evaluación de póliza que estima el valor de cada estado bajo una política fija y la mejora de póliza que es donde se actualiza la política eligiendo para cada estado, la acción que maximiza el valor esperado de la recompensa acumulada.

3. Explique en sus propias palabras el algoritmo de Iteración de Valor
   En nuestras palabras el algoritmo de iteración de valor se puede describir como un algoritmo de programación dinámica que busca encontrar una política optima, en donde este lo que hace es una actualización del valor para cada estado, se actualiza su valor tomando la máxima recompensa esperada que se puede obtener, considerando todas las posibles acciones y transiciones

4. En el laboratorio pasado, vimos que el valor de los premios obtenidos se mantienen constantes, ¿por qué?
   Se puede mencionar que en el laboratorio anterior el valor de la recompensa obtenidas se mantiene constante porque las recompensas asignadas para cada transición de estado-acción están definidas de manera fijo en el entorno del problema por lo que independientemente de cuantas veces se realice la acción especifica en un estado dado la recompensa inmediata será siempre la misma.

## Task 2

In [110]:
import numpy as np
import matplotlib.pyplot as plt
import random

### Defina los estados

In [111]:
S = {x for x in range(0, 9)}

### Defina las acciones

In [112]:
A = ['up', 'down', 'left', 'right']

In [113]:
goal_state = 8
obstacles = [2, 4]

### Probabilidades de transición


#       [ 0   1   2]
#       [ 3   4   5]
#       [ 6   7   8]

In [114]:
# Inicialización de las probabilidades de transición y recompensas
P = {s: {a: np.zeros(len(S)) for a in A} for s in S}
R = {s: {a: np.zeros(len(S)) for a in A} for s in S}

print(P)

{0: {'up': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'down': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'left': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'right': array([0., 0., 0., 0., 0., 0., 0., 0., 0.])}, 1: {'up': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'down': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'left': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'right': array([0., 0., 0., 0., 0., 0., 0., 0., 0.])}, 2: {'up': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'down': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'left': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'right': array([0., 0., 0., 0., 0., 0., 0., 0., 0.])}, 3: {'up': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'down': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'left': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'right': array([0., 0., 0., 0., 0., 0., 0., 0., 0.])}, 4: {'up': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'down': array([0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'left': array([0., 0., 0., 

In [115]:
P[0]['up'] = [1, 0, 0, 0, 0, 0, 0, 0, 0]
P[0]['down'] = [0, 0, 0, 1, 0, 0, 0, 0, 0]
P[0]['left'] = [1, 0, 0, 0, 0, 0, 0, 0, 0]
P[0]['right'] = [0, 1, 0, 0, 0, 0, 0, 0, 0]
# Estado 1
P[1]['up'] = [0, 1, 0, 0, 0, 0, 0, 0, 0]
P[1]['down'] = [0, 1, 0, 0, 0, 0, 0, 0, 0]
P[1]['left'] = [1, 0, 0, 0, 0, 0, 0, 0, 0]
P[1]['right'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
# Estado 2
P[2]['up'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
P[2]['down'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
P[2]['left'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
P[2]['right'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
# Estado 3
P[3]['up'] = [1, 0, 0, 0, 0, 0, 0, 0, 0]
P[3]['down'] = [0, 0, 0, 0, 0, 0, 1, 0, 0]
P[3]['left'] = [0, 0, 0, 1, 0, 0, 0, 0, 0]
P[3]['right'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
# Estado 4
P[4]['up'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
P[4]['down'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
P[4]['left'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
P[4]['right'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
# Estado 5
P[5]['up'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
P[5]['down'] = [0, 0, 0, 0, 0, 0, 0, 0, 1]
P[5]['left'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
P[5]['right'] = [0, 0, 0, 0, 0, 1, 0, 0, 0]
# Estado 6
P[6]['up'] = [0, 0, 1, 0, 0, 0, 0, 0, 0]
P[6]['down'] = [0, 0, 0, 0, 0, 0, 1, 0, 0]
P[6]['left'] = [0, 0, 0, 0, 0, 0, 1, 0, 0]
P[6]['right'] = [0, 0, 0, 0, 0, 0, 0, 1, 0]
# Estado 7
P[7]['up'] = [0, 0, 0, 0, 1, 0, 0, 0, 0]
P[7]['down'] = [0, 0, 0, 0, 0, 0, 0, 1, 0]
P[7]['left'] = [0, 0, 0, 0, 0, 0, 1, 0, 0]
P[7]['right'] = [0, 0, 0, 0, 0, 0, 0, 0, 1]
# Estado 8
P[8]['up'] = [0, 0, 0, 0, 0, 0, 0, 0, 1]
P[8]['down'] = [0, 0, 0, 0, 0, 0, 0, 0, 1]
P[8]['left'] = [0, 0, 0, 0, 0, 0, 0, 0, 1]
P[8]['right'] = [0, 0, 0, 0, 0, 0, 0, 0, 1]

In [116]:
def move(s, a):
    if a == 'up':
        return s - 3 if s >= 3 else s
    elif a == 'down':
        return s + 3 if s <= 5 else s
    elif a == 'left':
        return s - 1 if s % 3 != 0 else s
    elif a == 'right':
        return s + 1 if s % 3 != 2 else s
    else:
        return s

### Función de recompensa

In [117]:
for s in S:
    for a in A:
        s_prime = move(s, a)
        if s_prime == goal_state:
            R[s][a][s_prime] = 10
        elif s_prime in obstacles:
            R[s][a][s_prime] = -10
        elif s != s_prime:
            R[s][a][s_prime] = -1


In [118]:
policy = {s: random.choice(A) for s in S}

In [119]:
def value_iteration():
    V = np.zeros(len(S))
    gamma = 0.9
    epsilon = 0.001
    count = 0
    while True:
        count += 1
        delta = 0
        for s in S:
            v = V[s].copy()
            V[s] = max([sum([P[s][a][s_prime] * (R[s][a][s_prime] + gamma * V[s_prime])
                            for s_prime in S])
                        for a in A])
            delta = max(delta, abs(v - V[s]))
        if delta < epsilon:
            print(f'Converged after {count} iterations')
            break
    
    policy = {}
    for s in S:
        policy[s] = A[np.argmax([sum([P[s][a][s_prime] * (R[s][a][s_prime] + gamma * V[s_prime])
                                    for s_prime in S])
                                for a in A])]

    return V, policy

In [120]:
V, policy = value_iteration()
print("Optimal Value Function:")
print(V)
print("Optimal Policy:")
print(policy)

Converged after 89 iterations
Optimal Value Function:
[70.18153585 62.16338227  0.         79.09153585  0.         99.99153585
 88.99153585 99.99153585 99.99153585]
Optimal Policy:
{0: 'down', 1: 'left', 2: 'down', 3: 'down', 4: 'up', 5: 'down', 6: 'right', 7: 'right', 8: 'down'}
